name: Test

on:
  push:

jobs:
  test:
    if: startsWith(github.event.head_commit.message, 'chore(release)')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.24.4
    - name: Use Node.js 15
      uses: actions/setup-node@v2
      with:
        node-version: 15
        cache: 'pnpm'
    - name: Install
      run: |
        pnpm install --filter ./.github/actions
    - name: Upload to Azure
      uses: ci010/upload-blob-to-azure@master
      env:
        AZURE_ACCOUNT_KEY: ${{ secrets.AZURE_ACCOUNT_KEY }}
      with:
        account: xmcl
        container: releases
        directory: ./assets
    - name: Update Web Page
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Deploy
        token: ${{ secrets.PAT_GITHUB_TOKEN }}
        ref: 'master'
        repo: 'voxelum/xmcl-page'
